name: py311
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - category_encoders=2.9.0=pyhcf101f3_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.19=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.61.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.53=hfab5511_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.1=h1b79a29_1
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.0=py311had1e860_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_2
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py311hb52a7e5_2
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311h5bb9006_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qhull=2020.2=h420ef59_5
  - rapidfuzz=3.14.3=py311h251fd82_1
  - readline=8.3=h46df422_0
  - scikit-learn=1.8.0=np2py311hece8d6f_1
  - scipy=1.16.3=py311ha71c161_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py311h09efe57_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.4=py311h9408147_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - unicodedata2=17.0.0=py311h9408147_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zeromq=4.3.5=h888dc83_9
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - flatbuffers==25.12.19
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - keras==3.13.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - protobuf==6.33.2
      - requests==2.32.5
      - rich==14.2.0
      - scikeras==0.13.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - urllib3==2.6.2
      - werkzeug==3.1.4
      - wrapt==2.0.1
prefix: /opt/anaconda3/envs/py311
